# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1e12e608ca0a9afcd087a76c1152fa47"
name = "designer"
handle = "designer-17"
application_url = "https://app.printlabs.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://app.printlabs.com/auth/callback",
  "https://app.printlabs.com/auth/shopify/callback",
  "https://app.printlabs.com/api/auth/callback"
]

[app_proxy]
url = "https://app.printlabs.com"
subpath = "designer"
prefix = "apps"

[pos]
embedded = false
