name = "canvas-api-pdp"
type = "theme"

[settings]
  [[settings.fields]]
    id = "use_modern_theme_support"
    type = "checkbox"
    label = "Use modern theme support"
    default = true
    info = "Enable support for Horizons 2025 themes"

